version: "3"

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /opt/okkake
    volumes:
      - .:/opt/okkake:cached
      - data-bundle:/usr/local/bundle
      - data-node-modules:/opt/okkake/node_modules
      - ${HOME}/.aws:/root/.aws
    links:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgis://postgres:password@postgres:5432
      ELASTICSEARCH_URL: http://elasticsearch:9200
      REDIS_URL: redis://redis:6379/0
      CACHE_REDIS_URL: redis://redis:6379/1
      SESSION_REDIS_URL: redis://redis:6379/2
      BINDING: 0.0.0.0

  web:
    <<: *app
    command: ./bin/rails s
    ports:
      - 3000:3000

  worker:
    <<: *app
    command: ./bin/sidekiq

  postgres:
    image: kanotan/postgres:13.4-postgis-3.2
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: kanotan/redis:5.0
    volumes:
      - data-redis:/data
    ports:
      - 6379:6379

volumes:
  data-bundle:
    driver: local
  data-node-modules:
    driver: local
  data-postgres:
    driver: local
  data-redis:
    driver: local
