default: &default
  adapter: postgis
  encoding: unicode
  schema_search_path: public
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: okkake_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: okkake_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: okkake
  url: <%= ENV['DATABASE_URL'] %>
